name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  intl_utils: 2.8.7
  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4
  build_runner: 2.4.9
  firebase_core: 2.27.0
  firebase_auth: 4.17.8
  flutter_modular: 6.3.3
  flutter_svg: 2.0.11
  shared_preferences: 2.2.3
  flutter_screenutil: 5.9.3
  flutter_dotenv: 5.2.1
  dio: 5.7.0
  json_annotation: 4.9.0
  path_provider: 2.1.4
  logger: 2.4.0
  lottie: 3.1.3
  google_sign_in: 6.2.2
  intl: 0.19.0
  retrofit: 4.4.1
  flutter_easyloading: 3.0.5
  package_info_plus: 5.0.1
  jwt_decoder: 2.0.1
  cached_network_image: 3.4.0
  shimmer: 3.0.0
  rxdart: 0.28.0
  dropdown_button2: 2.3.9
  board_datetime_picker: 2.3.0
  bottom_picker: 2.11.0
  loading_indicator: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    # build_runner
  freezed: 2.5.2
  json_serializable: 6.8.0
  flutter_lints: 4.0.0
  flutter_gen_runner:
  test: 1.25.7
  retrofit_generator: 9.1.5
  mocktail: 1.0.4
  bloc_test: 9.1.7
  firebase_auth_mocks: 0.13.0
  google_sign_in_mocks: 0.3.0
  # config icon app
  flutter_launcher_icons: 0.14.3
  change_app_package_name: 1.5.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true

flutter_icons:
  android: true
  ios: true
  # image_path: "assets/icons/ic_logo_dev.png"
  remove_alpha_ios: true
